"""empty message

Revision ID: 7fd2fff59a05
Revises: f835859f7bd8
Create Date: 2020-12-11 01:05:25.273486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd2fff59a05'
down_revision = 'f835859f7bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_request',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_requests',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_request.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'user_request_id')
    )
    op.create_table('topping_request',
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.Column('topping', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topping'], ['topping.id'], ),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_request.id'], ),
    sa.PrimaryKeyConstraint('user_request_id', 'topping')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topping_request')
    op.drop_table('order_requests')
    op.drop_table('user_request')
    op.drop_table('receipt')
    op.drop_table('order')
    # ### end Alembic commands ###
